######################################################################
# Automatically generated by qmake (2.01a) ven feb 4 11:17:02 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mythread.h pulsanti.h
SOURCES += main.cpp
